import { chromium } from '@playwright/test';
const [,, url, out, w='1280', h='900', full='1'] = process.argv;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: +w, height: +h } });
const errs=[]; p.on('console', m => { if (m.type()==='error') errs.push(m.text()); });
await p.goto(url, { waitUntil: 'networkidle' });
await p.waitForTimeout(500);
await p.screenshot({ path: out, fullPage: full==='1' });
console.log('errors:', errs.join(' | ') || 'none');
await b.close();
