// <auto-generated />
using System;
using System.Collections.Generic;
using ExamPrep.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamPrep.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005145343_ScenariosPerForm")]
    partial class ScenariosPerForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamPrep.Api.Data.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FeedbackEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("FeedbackExposed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OmittedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("PassPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Percent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("PointsMax")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ScoringPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StartedAsClean")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeUsedSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "DeadlineAt");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.AttemptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("DomainCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FeedbackRevealed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("LearningOptionIds")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("OptionOrder")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScenarioId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ScoredOptionIds")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("SelectedOptionIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("AttemptId", "Position")
                        .IsUnique();

                    b.ToTable("attempt_items", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("certifications", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BankTarget")
                        .HasColumnType("integer");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Objectives")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId", "Code")
                        .IsUnique();

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.ExamProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AllowedQuestionTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("AppointmentDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("BlueprintVersion")
                        .HasColumnType("text");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DomainWeights")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ExamDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OfficialScoreReference")
                        .HasColumnType("text");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ScenariosPerForm")
                        .HasColumnType("integer");

                    b.Property<string>("ScoringPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SimulatorPassPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.PrimitiveCollection<List<string>>("SourceIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_profiles_current")
                        .HasFilter("\"IsCurrent\" = true");

                    b.HasIndex("CertificationId", "Version")
                        .IsUnique();

                    b.ToTable("exam_profiles", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Created")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewVersions")
                        .HasColumnType("integer");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Unchanged")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.LoginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail", "CreatedAt");

                    b.ToTable("login_tokens", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.OutboxEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("dev_outbox", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("FamilyId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.QuestionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CorrectOptionIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DifficultyBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DomainCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Originality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Provenance")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScenarioId")
                        .HasColumnType("text");

                    b.Property<int>("SelectCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCheckedAt")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("SourceIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusNote")
                        .HasColumnType("text");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("Status");

                    b.HasIndex("QuestionId", "VersionNo")
                        .IsUnique();

                    b.ToTable("question_versions", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Scenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("scenarios", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CheckedAt")
                        .HasColumnType("text");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conflicts")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PublishedAt")
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Restrictions")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.VerifiedLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId", "Locale")
                        .IsUnique();

                    b.ToTable("verified_languages", (string)null);
                });

            modelBuilder.Entity("ExamPrep.Api.Data.AttemptItem", b =>
                {
                    b.HasOne("ExamPrep.Api.Data.Attempt", null)
                        .WithMany("Items")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamPrep.Api.Data.QuestionVersion", "QuestionVersion")
                        .WithMany()
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Domain", b =>
                {
                    b.HasOne("ExamPrep.Api.Data.Certification", null)
                        .WithMany("Domains")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPrep.Api.Data.ExamProfile", b =>
                {
                    b.HasOne("ExamPrep.Api.Data.Certification", null)
                        .WithMany("Profiles")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPrep.Api.Data.QuestionVersion", b =>
                {
                    b.HasOne("ExamPrep.Api.Data.Question", "Question")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamPrep.Api.Data.VerifiedLanguage", b =>
                {
                    b.HasOne("ExamPrep.Api.Data.Certification", null)
                        .WithMany("Languages")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Attempt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Certification", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("Languages");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("ExamPrep.Api.Data.Question", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
